name: ML_intro
channels:
  - conda-forge
dependencies:
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - matplotlib
  - numpy
  - pandas
  - pip
  - plotly
  - python=3.11
  - scikit-learn
  - scipy
